### ISSUE TITLE
Memory problem while running project with 100+ classes

### ISSUE THREAD

**Issue by uuf6429** [seanmorris/php-wasm#34]
After getting the demo to work recently, I tried to make it work for a side project I'm on.

The project is based on composer and since I couldn't find a way to populate/fill-in the WASM virtual filesystem (or any reference on how it would work), I used a [tool](https://github.com/ClassPreloader/ClassPreloader) concatenates all the relevant/used classes in one big PHP file - about 106 classes/traits/interfaces and 15k lines in total. Finally, with some fiddling, I put the contents of that file in `<script type="text/php"` as in the demo.

The PHP file by itself worked fine in PHP, however php-wasm fails with the following:
```text
php-web.wasm:0x6fe3 Uncaught (in promise) RuntimeError: memory access out of bounds
    at php-web.wasm:0x6fe3
    at invoke_ii (php-web.mjs:8:124829)
    at php-web.wasm:0x451529
    at invoke_iiii (php-web.mjs:8:124532)
    at php-web.wasm:0x7fb438
    at Module._pib_run (php-web.mjs:8:123160)
    at Object.ccall (php-web.mjs:8:118781)
    at PhpBase.mjs:63:38
```

Some thing I tried:
1. running the big php script by itself in PHP; it worked fine
2. running phpinfo(); it also worked fine - PHP 8.2 with some 100mb of memory
3. running ini_set for memory_limit with 1G for the big script - still failed; no difference

To me it feels like the failure could be coming at the parsing or an earlier stage. Unfortunately, my knowledge in webassembly is very limited and I gave up as soon as I saw the dissassembled code. I don't know what else to try debugging this.

It's worth nothing that there is no PHP framework or an special extensions in my project - it doesn't even use a db.
So it's frankly baffling to hear people running drupal or wordpress (with thousands of files) over this tool.

I'm running Chrome 118 x64 on Windows 11, if that helps.

**Comment by uuf6429** [comment]
Since the recent changes & deployment, the error changed to:
```text
PhpWeb.mjs:77 RuntimeError: table index is out of bounds
    at php-web.wasm:0x1bc58d
    at php-web.wasm:0x20e7d6
    at php-web.wasm:0x9ca0
    at invoke_viii (php-web.mjs:8:129659)
    at php-web.wasm:0x112284
    at php-web.wasm:0x29c9b1
    at php-web.wasm:0x20e608
    at php-web.wasm:0x71e1
    at invoke_ii (php-web.mjs:8:129509)
    at php-web.wasm:0x44d5c5
```

I also noticed that the problem is not related to parsing PHP, but rather the size of the code; a simple `static $x = 'very long string'; phpinfo();` fails after a certain string length (regardless of the actual content).

**Comment by uuf6429** [comment]
I've managed to overcome this after following the instructions from https://github.com/soyuka/php-wasm.

**Comment by Potherca** [comment]
@uuf6429 Could you specify which instruction exactly? Would very much also like to make a client-side version of a PHP project I'm involved in...
