### ISSUE TITLE
Can't run version 8.3

### ISSUE THREAD

**Issue by kazzkzpk** [seanmorris/php-wasm#50]
I build a 8.3 version from strach, using php-wasm-builder, and got that browser console error.

```
PhpWeb.mjs:162 TypeError: Cannot read properties of undefined (reading 'request')
    at PhpWeb._enqueue (PhpWeb.mjs:47:19)
    at PhpWeb.run (PhpBase.mjs:181:15)
    at PhpWeb.<anonymous> (PhpWeb.mjs:160:8)
    at postRun (PhpBase.mjs:42:10)
    at callRuntimeCallbacks (php-web.mjs:9:32725)
    at postRun (php-web.mjs:9:14900)
    at doRun (php-web.mjs:9:699687)
    at run (php-web.mjs:9:699844)
    at runCaller (php-web.mjs:9:698882)
    at removeRunDependency (php-web.mjs:9:15716)
```
    
Try running that part I found on README:

```
<script async type = "module" src = "https://cdn.jsdelivr.net/npm/php-wasm@0.0.9-alpha-12/php-tags.mjs"></script>

<script type = "text/php" data-stdout = "#output" data-stderr = "#error" data-libs = '[
  {"url": "https://unpkg.com/php-wasm-yaml/php8.3-yaml.so", "ini": true},
  {"url": "https://unpkg.com/php-wasm-yaml/libyaml.so", "ini": false}
]'><?php
  print yaml_emit([1,2,3,"string",["k1" => "value", "k2" => "value2", "k3" => "value3"],"now" => date("Y-m-d h:i:s")]);
</script>
```

And got same error.
Tried run on Chrome, Brave and Edge.

**Comment by kazzkzpk** [comment]
I just found that navigator.locks.request dont work on insecure connections (like a simple Docker).

Just put a polyfill, and it runs:
`<script src="https://unpkg.com/web-locks-polyfill/dist/web-locks-polyfill.js"></script>`

Thank you.
